"""v1.00 add index

Revision ID: f04ab5fcbd7b
Revises: f0f3096c1747
Create Date: 2017-09-15 20:19:10.310924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04ab5fcbd7b'
down_revision = 'f0f3096c1747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=False)
    op.create_index(op.f('ix_tag_title'), 'tag', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_title'), table_name='tag')
    op.drop_index(op.f('ix_post_title'), table_name='post')
    # ### end Alembic commands ###
